name: Filip's personal blog
description: Blogging about marketing the Kendo way
meta_description: ""

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'blog url'
author:         'Filip Komnenović'
